Update strict-lint.yaml

diff --git a/.github/workflows/strict-lint.yaml b/.github/workflows/strict-lint.yaml
--- a/.github/workflows/strict-lint.yaml
+++ b/.github/workflows/strict-lint.yaml
@@ -30,23 +30,24 @@ jobs:
         id: eslint
 
       # - name: check for ESLint result
+      #   if: steps.eslint.outcome == 'failure'
       #   run: |
       #     echo "ESLint found issues. Failing the workflow."
-      #     exit 1 
+      #     exit 1
           
-      # - name: block PR if ESLint fails
-      #   if: steps.eslint.outcome == 'failure'
-      #   uses: actions/github-script@v6
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     script: |
-      #       github.rest.pulls.createReview({
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         pull_number: context.issue.number,
-      #         event: 'REQUEST_CHANGES',
-      #         body: 'ESLint check failed. Please fix all linting issues (including warnings) before merging.'
-      #       })
+      - name: block PR if ESLint fails
+        if: steps.eslint.outcome == 'failure'
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            github.rest.pulls.createReview({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              pull_number: context.issue.number,
+              event: 'REQUEST_CHANGES',
+              body: 'ESLint check failed. Please fix all linting issues (including warnings) before merging.'
+            })
 
       - name: setup NodeJS for Build
         uses: actions/setup-node@v4
@@ -58,7 +59,7 @@ jobs:
         run: npm ci
 
       - name: build Project from React Files
-        run: |
+        run: | 
           CI=false
           npm run build
 
@@ -70,8 +71,8 @@ jobs:
         run: |
           netlify deploy \
             --dir build \
-            --site ${{ secrets.SITEID }} \
-            --auth ${{ secrets.TOKEN }} \
+            --site ${{ secrets.NETLIFY_SITE_ID_USER }} \
+            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
             --json \
             --alias "healthcare-${{ github.actor }}" \
             > deploy_output.json
